name: Cleanup Expired Artifacts

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * 0"

jobs:
  cleanup:
    uses: iyulab/shared/.github/workflows/cleanup-expired-artifacts.yml@a812e4874638261d7f268e2a0af904cbf026dbd6
