name: Cleanup Expired Artifacts

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * 0"

jobs:
  cleanup:
    uses: iyulab/shared/.github/workflows/cleanup-expired-artifacts.yml@a2e48ce2d6e8f5819c0ca99025734f625ec75f8a
